export const data = [
  {
    category: "cds",
    name: "Earth A.d. - The Misfits",
    genre: "hardcore punk",
    price: 14900,
    released: "1983",
    stock: 5,
    img: "https://images.coveralia.com/audio/thumbs/78426g.jpg",
    imgDetail: "https://upload.wikimedia.org/wikipedia/en/8/80/Misfits_-_Earth_A.D._cover.jpg",
    songList: [
      "Earth A.D.",
      "Queen Wasp",
      "Devilock",
      "Death Comes Ripping",
      "Green Hell",
      "Mommy, Can I Go Out and Kill Tonight?",
      "Wolfs Blood",
      "Demonomania",
      "Bloodfeast",
      "Hellhound",
      "Die, Die My Darling",
      "We Bite"
    ]
  },
  {
    category: "cds",
    name: "Full Speed Ahead - D.r.i.",
    genre: "thrash",
    price: 12900,
    released: "1995",
    stock: 4,
    img: "https://images.coveralia.com/audio/thumbs/236100g.jpg",
    imgDetail: "https://upload.wikimedia.org/wikipedia/en/d/da/Fullspeedahead.JPG",
    songList: [
      "Problem Addict",
      "I'm the Liar",
      "Under the Overpass",
      "They Don't Care",
      "Drawn and Quartered",
      "No End",
      "Wages of Sin",
      "Syringes in the Sandbox",
      "Who Am I?",
      "Girl With a Gun",
      "Dead Meat",
      "Down to the Wire",
      "Level 7",
      "Broke",
      "Sucker",
      "Underneath the Surface"
    ]
  },
  {
    category: "cds",
    name: "Bleach - Nirvana",
    genre: "grunge",
    price: 14900,
    released: "1989",
    stock: 3,
    img: "https://images.coveralia.com/audio/thumbs/2344g.jpg",
    imgDetail: "https://upload.wikimedia.org/wikipedia/en/a/a1/Nirvana-Bleach.jpg",
    songList: [
      "Blew",
      "Floyd the Barber",
      "About a Girl",
      "School",
      "Love Buzz",
      "Paper Cuts",
      "Negative Creep",
      "Scoff",
      "Swap Meet",
      "Mr. Moustache",
      "Sifting"
    ]
  },
  {
    category: "vinyls",
    name: "13 Songs - Fugazi",
    genre: "hardcore",
    released: "1989",
    price: 14900,
    stock: 10,
    img: "https://images.coveralia.com/audio/thumbs/250918g.jpg",
    imgDetail: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Fugazi_-_13_Songs_cover.PNG/220px-Fugazi_-_13_Songs_cover.PNG",
    songList: [
      "Waiting Room",
      "Bulldog Front",
      "Bad Mouth",
      "Burning",
      "Give Me The Cure",
      "Suggestion",
      "Glue Man",
      "Margin Walker",
      "And The Same",
      "Burning Too",
      "Provisional",
      "Lockdown",
      "Promises"
  ]
  },
  {
    category: "vinyls",
    name: "Songs Of Praise - The Adicts",
    genre: "punk rock",
    released: "1981",
    price: 14900,
    stock: 2,
    img: "https://images.coveralia.com/audio/thumbs/128123g.jpg",
    imgDetail: "https://upload.wikimedia.org/wikipedia/en/thumb/2/22/Songsofpraise.jpg/220px-Songsofpraise.jpg",
    songList: [
      "England",
      "Hurt",
      "Just Like Me",
      "Tango",
      "Telepathic People",
      "Mary Whitehouse",
      "Distortion",
      "Get Adicted",
      "Viva la Revolution",
      "Calling Calling",
      "In the Background",
      "Dynasty",
      "Peculiar Music",
      "Numbers",
      "Sensitive",
      "Songs of Praise"
    ]
  },
  {
    category: "vinyls",
    name: "D.R.I. - 4 Of A Kind",
    genre: "thrash",
    released: "1988",
    price: 31900,
    stock: 80,
    img: "https://images.coveralia.com/audio/thumbs/128123g.jpg",
    imgDetail: "https://upload.wikimedia.org/wikipedia/en/thumb/2/22/Songsofpraise.jpg/220px-Songsofpraise.jpg",
    songList: [
      "All for Nothing",
      "Manifest Destiny",
      "Gone Too Long",
      "Do the Dream",
      "Shut-Up!",
      "Modern World",
      "Think for Yourself",
      "Slumlord",
      "Dead in a Ditch",
      "Suit and Tie Guy",
      "Man Unkind",
    ]
  },
  {
    category: "cds",
    name: "Death - Leprosy",
    genre: "Death metal",
    released: "1988",
    price: 13900,
    stock: 80,
    img: "https://images.coveralia.com/audio/thumbs/128123g.jpg",
    imgDetail: "https://upload.wikimedia.org/wikipedia/en/thumb/2/22/Songsofpraise.jpg/220px-Songsofpraise.jpg",
    songList: [
      "Leprosy",
      "Born Dead",
      "Forgotten Past",
      "Left To Die",
      "Pull The Plug",
      "Open Casket",
      "Primitive Ways",
      "Choke On It",
    ]
  },
  {
    category: "vinyls",
    name: "Misfits - Walk Among Us",
    genre: "Hardcore punk",
    released: "1982",
    price: 24900,
    stock: 80,
    img: "https://images.coveralia.com/audio/thumbs/128123g.jpg",
    imgDetail: "https://upload.wikimedia.org/wikipedia/en/thumb/2/22/Songsofpraise.jpg/220px-Songsofpraise.jpg",
    songList: [
      "20 Eyes",
      "I Turned Into A Martian",
      "All Hell Breaks Loose",
      "Vampira",
      "Nike A Go Go",
      "Hate Breeders",
      "Mommy, Can I Go Out + Kill Tonight (Live)",
      "Night Of The Living Dead",
      "Skulls",
      "Violent World",
      "Devils Whorehouse",
      "Astro Zombies",
      "Braineaters",
    ]
  },
  {
    category: "vinyls",
    name: "Black Flag – Damaged",
    genre: "Hardcore punk",
    released: "1981",
    price: 32000,
    stock: 80,
    img: "https://images.coveralia.com/audio/thumbs/128123g.jpg",
    imgDetail: "https://upload.wikimedia.org/wikipedia/en/thumb/2/22/Songsofpraise.jpg/220px-Songsofpraise.jpg",
    songList: [
      "Rise Above",
      "Spray Paint",
      "Six Pack",
      "What I See",
      "TV Party",
      "Thirsty and Miserable",
      "Police Story",
      "Gimmie Gimmie Gimmie",
      "Depression",
      "Room 13",
      "Damaged II",
      "No More",
      "Padded Cell",
      "Life of Pain",
      "Damaged I"
    ]
  },
  {
    category: "cds",
    name: "Bad Religion - No Control",
    genre: "Punk rock",
    released: "1989",
    price: 12900,
    stock: 80,
    img: "https://images.coveralia.com/audio/thumbs/128123g.jpg",
    imgDetail: "https://upload.wikimedia.org/wikipedia/en/thumb/2/22/Songsofpraise.jpg/220px-Songsofpraise.jpg",
    songList: [
      "Change of Ideas",
      "Big Bang",
      "No Control",
      "Sometimes I Feel Like",
      "Automatic Man",
      "I Want to Conquer the World",
      "Sanity",
      "Henchman",
      "It Must Look Pretty Appealing",
      "You",
      "Progress",
      "I Want Something More",
      "Anxiety",
      "Billy",
      "The World Won't Stop"
    ]
  },
  {
    category: "vinyls",
    name: "Suicidal Tendencies - Suicidal Tendencies",
    genre: "Hardcore punk",
    released: "1983",
    price: 26900,
    stock: 80,
    img: "https://images.coveralia.com/audio/thumbs/128123g.jpg",
    imgDetail: "https://upload.wikimedia.org/wikipedia/en/thumb/2/22/Songsofpraise.jpg/220px-Songsofpraise.jpg",
    songList: [
      "Suicide's An Alternative / You'll Be Sorry",
      "Two Sided Politics",
      "I Shot the Devil",
      "Subliminal",
      "Won't Fall in Love Today",
      "Institutionalized",
      "Memories of Tomorrow",
      "Possessed",
      "I Saw Your Mommy",
      "Fascist Pig",
      "I Want More",
      "Suicidal Failure",
    ]
  },
];
