export const data = [
  {
    id: "01",
    category: "cds",
    name: "Earth A.d. - The Misfits",
    genre: "hardcore punk",
    price: "$14.900",
    released: "1983",
    stock: 5,
    img: "https://images.coveralia.com/audio/thumbs/78426g.jpg",
    imgDetail: "https://upload.wikimedia.org/wikipedia/en/8/80/Misfits_-_Earth_A.D._cover.jpg",
    songList: [
      "Earth A.D.",
      "Queen Wasp",
      "Devilock",
      "Death Comes Ripping",
      "Green Hell",
      "Mommy, Can I Go Out and Kill Tonight?",
      "Wolfs Blood",
      "Demonomania",
      "Bloodfeast",
      "Hellhound",
      "Die, Die My Darling",
      "We Bite"
    ]
  },
  {
    id: "02",
    category: "cds",
    name: "Full Speed Ahead - D.r.i.",
    genre: "thrash",
    price: "$12.900",
    released: "1995",
    stock: 4,
    img: "https://images.coveralia.com/audio/thumbs/236100g.jpg",
    imgDetail: "https://upload.wikimedia.org/wikipedia/en/d/da/Fullspeedahead.JPG",
    songList: [
      "Problem Addict",
      "I'm the Liar",
      "Under the Overpass",
      "They Don't Care",
      "Drawn and Quartered",
      "No End",
      "Wages of Sin",
      "Syringes in the Sandbox",
      "Who Am I?",
      "Girl With a Gun",
      "Dead Meat",
      "Down to the Wire",
      "Level 7",
      "Broke",
      "Sucker",
      "Underneath the Surface"
    ]
  },
  {
    id: "03",
    category: "cds",
    name: "Bleach - Nirvana",
    genre: "grunge",
    price: "$14.900",
    released: "1989",
    stock: 3,
    img: "https://images.coveralia.com/audio/thumbs/2344g.jpg",
    imgDetail: "https://upload.wikimedia.org/wikipedia/en/a/a1/Nirvana-Bleach.jpg",
    songList: [
      "Blew",
      "Floyd the Barber",
      "About a Girl",
      "School",
      "Love Buzz",
      "Paper Cuts",
      "Negative Creep",
      "Scoff",
      "Swap Meet",
      "Mr. Moustache",
      "Sifting"
    ]
  },
  {
    id: "04",
    category: "vinyls",
    name: "13 Songs - Fugazi",
    genre: "hardcore",
    released: "1989",
    price: "$14.900",
    stock: 10,
    img: "https://images.coveralia.com/audio/thumbs/250918g.jpg",
    imgDetail: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Fugazi_-_13_Songs_cover.PNG/220px-Fugazi_-_13_Songs_cover.PNG",
    songList: [
      "Waiting Room",
      "Bulldog Front",
      "Bad Mouth",
      "Burning",
      "Give Me The Cure",
      "Suggestion",
      "Glue Man",
      "Margin Walker",
      "And The Same",
      "	Burning Too",
      "Provisional",
      "Lockdown",
      "Promises"
  ]
  },
  {
    id: "05",
    category: "vinyls",
    name: "Songs Of Praise - The Adicts",
    genre: "punk rock",
    released: "1981",
    price: "$14.900",
    stock: 2,
    img: "https://images.coveralia.com/audio/thumbs/128123g.jpg",
    imgDetail: "https://upload.wikimedia.org/wikipedia/en/thumb/2/22/Songsofpraise.jpg/220px-Songsofpraise.jpg",
    songList: [
      "England",
      "Hurt",
      "Just Like Me",
      "Tango",
      "Telepathic People",
      "Mary Whitehouse",
      "Distortion",
      "Get Adicted",
      "Viva la Revolution",
      "Calling Calling",
      "In the Background",
      "Dynasty",
      "Peculiar Music",
      "Numbers",
      "Sensitive",
      "Songs of Praise"
    ]
  },
];
